import { realpathSync } from 'node:fs';
import { sep } from 'node:path';
import { Project, ts } from 'ts-morph';
import { loadDiscoveryTsconfig, resolveTsconfigPath } from './contracts-fast.js';
import type { ContractSource, RouteDescriptor } from './types.js';

/**
 * `types: 'standalone'` — resolve every route's request/response types with the
 * TypeScript checker and print them as self-contained type text.
 *
 * The default (`'reference'`) emits `Awaited<ReturnType<import('<controller>')…>>`
 * and `import type` statements pointing at server source, so whatever type-checks
 * the generated client also type-checks the server (its decorators, its Node
 * types, its whole import graph). That is fine when client and server share one
 * tsconfig and not fine when the client lives in another package — a Vite SPA, a
 * mobile app, a shared `packages/client` — which then drags in the entire API.
 *
 * Standalone mode asks the checker for what each handler actually returns
 * (inferred return types included) and what its `@Body()`/`@Query()` accept, and
 * prints that. Named types declared in the app (interfaces, classes, type aliases,
 * enums) are hoisted into `types.ts` and referenced by name; everything else —
 * anonymous object types, library types such as Drizzle's inferred rows — is
 * inlined structurally. The generated files then import nothing from the server.
 *
 * A validation pipe's schema is preferred over the parameter annotation when it
 * is a Standard Schema (zod ≥ 3.24, valibot, arktype): `@Body(new ZodPipe(s))`
 * types the body as the schema's INPUT (`.default()` fields optional), which is
 * what a client sends, rather than the parsed output the handler receives.
 */

/** Where hoisted declarations are referenced from inside api.ts. */
export const STANDALONE_TYPES_NAMESPACE = '$types';

/** Placeholder the printer writes before a hoisted name; resolved per output file. */
const REF = '\u0000ref:';

export interface StandaloneTypesOptions {
  /** Project root (for input tracking). */
  cwd: string;
  /** tsconfig of the server app (`app.tsconfig`, else `<cwd>/tsconfig.json`). */
  tsconfig?: string | undefined;
}

export interface StandaloneTypesResult {
  /** The routes, their body/query/response replaced by self-contained type text. */
  routes: RouteDescriptor[];
  /** `types.ts` source (hoisted named types), or null when nothing was hoisted. */
  typesModule: string | null;
  /** Local (non-node_modules) source files the program read — generate inputs. */
  inputs: string[];
}

export function resolveStandaloneTypes(
  routes: RouteDescriptor[],
  opts: StandaloneTypesOptions,
): StandaloneTypesResult {
  const tsconfigPath = resolveTsconfigPath(opts.cwd, opts.tsconfig);
  const loaded = loadDiscoveryTsconfig(tsconfigPath);
  const project = new Project({
    compilerOptions: { ...(loaded.options ?? {}), noEmit: true, strict: true },
    skipAddingFilesFromTsConfig: true,
  });

  const files = new Set<string>();
  for (const r of routes) if (r.controllerRef) files.add(r.controllerRef.filePath);
  for (const f of files) project.addSourceFileAtPathIfExists(f);

  const program = project.getProgram().compilerObject;
  const checker = program.getTypeChecker();
  const printer = new TypePrinter(checker, program);

  const out = routes.map((route) => {
    const cs = route.contract?.contractSource;
    const ref = route.controllerRef;
    if (!cs || !ref) return route;
    const handler = findHandler(program, checker, ref.filePath, ref.className, ref.methodName);
    if (!handler) return route;
    const next = resolveRoute(printer, checker, handler, cs);
    return next ? { ...route, contract: { ...route.contract, contractSource: next } } : route;
  });

  const inputs = program
    .getSourceFiles()
    .filter((sf) => !program.isSourceFileDefaultLibrary(sf) && !isExternal(sf.fileName))
    .map((sf) => sf.fileName)
    .sort();

  const declarations = printer.declarations();
  return {
    routes: out.map((r) => bindRefs(r, `${STANDALONE_TYPES_NAMESPACE}.`)),
    typesModule:
      declarations.length > 0
        ? [
            '// Generated by @dudousxd/nestjs-codegen. Do not edit.',
            '// Types the API routes use, resolved from the server source (`types: "standalone"`).',
            '',
            ...declarations.map((d) => d.split(REF).join('')),
            '',
          ].join('\n')
        : null,
    inputs,
  };
}

// ---------------------------------------------------------------------------
// Route resolution
// ---------------------------------------------------------------------------

interface Handler {
  signature: ts.Signature;
  /** The handler's declaration, for reading parameter decorators. */
  declaration: ts.SignatureDeclaration;
}

function findHandler(
  program: ts.Program,
  checker: ts.TypeChecker,
  filePath: string,
  className: string,
  methodName: string,
): Handler | null {
  const sf = program.getSourceFile(filePath);
  if (!sf) return null;
  const cls = sf.statements.find(
    (s): s is ts.ClassDeclaration => ts.isClassDeclaration(s) && s.name?.text === className,
  );
  if (!cls?.name) return null;
  const classSymbol = checker.getSymbolAtLocation(cls.name);
  if (!classSymbol) return null;
  // The INSTANCE type, so an inherited (factory-produced) handler resolves with
  // the derived class's type arguments already substituted.
  const instance = checker.getDeclaredTypeOfSymbol(classSymbol);
  const prop = checker.getPropertyOfType(instance, methodName);
  if (!prop) return null;
  const signature = checker.getTypeOfSymbolAtLocation(prop, cls).getCallSignatures()[0];
  const declaration = signature?.getDeclaration();
  if (!signature || !declaration) return null;
  return { signature, declaration };
}

function resolveRoute(
  printer: TypePrinter,
  checker: ts.TypeChecker,
  handler: Handler,
  cs: ContractSource,
): ContractSource | null {
  const next: ContractSource = { ...cs, standalone: true };

  // Streams keep the discovered element type and binary routes are `RawResponse<Blob>`
  // regardless; every other response is what the handler resolves to.
  if (!cs.stream && !cs.binaryResponse) {
    const returned = handler.signature.getReturnType();
    const awaited = checker.getAwaitedType(returned) ?? returned;
    next.response = printer.print(awaited);
    next.responseRef = null;
  }

  // Keep a body/query the static pass rendered from a filter (`@ApplyFilter`) —
  // the filter extension owns that shape.
  const body = requestType(printer, checker, handler, 'Body');
  if (body !== undefined && !(cs.filterSource === 'body' && cs.filterFields?.length)) {
    next.body = body;
    next.bodyRef = null;
  }
  const query = requestType(printer, checker, handler, 'Query');
  if (query !== undefined && !(cs.filterSource === 'query' && cs.filterFields?.length)) {
    next.query = query;
    next.queryRef = null;
  }
  return next;
}

/**
 * The type a client sends for `@Body()` / `@Query()`: the whole-object parameter
 * (`@Body()`, `@Body(pipe)`) or, failing that, the named-property parameters
 * (`@Body('title')`) as one object. `undefined` when the handler has none.
 */
function requestType(
  printer: TypePrinter,
  checker: ts.TypeChecker,
  handler: Handler,
  decoratorName: 'Body' | 'Query',
): string | undefined {
  const named: string[] = [];
  const params = handler.declaration.parameters;
  for (const [index, param] of params.entries()) {
    const decorator = findDecorator(param, decoratorName);
    if (!decorator) continue;
    const symbol = handler.signature.getParameters()[index];
    const declared = symbol ? checker.getTypeOfSymbol(symbol) : checker.getTypeAtLocation(param);
    const args = ts.isCallExpression(decorator.expression) ? decorator.expression.arguments : [];
    const first = args[0];
    const property = first && ts.isStringLiteralLike(first) ? first.text : null;
    const schemaInput = pipeSchemaInput(checker, property === null ? args : args.slice(1));
    const type = schemaInput ?? declared;
    if (property === null) return printer.print(type);
    const optional = !!param.questionToken || !!param.initializer;
    named.push(
      `${propertyKey(property)}${optional ? '?' : ''}: ${printer.print(optional ? checker.getNonNullableType(type) : type)}`,
    );
  }
  return named.length > 0 ? `{ ${named.join('; ')} }` : undefined;
}

function findDecorator(node: ts.Node, name: string): ts.Decorator | undefined {
  const decorators = ts.canHaveDecorators(node) ? ts.getDecorators(node) : undefined;
  return decorators?.find((d) => {
    const callee = ts.isCallExpression(d.expression) ? d.expression.expression : d.expression;
    return ts.isIdentifier(callee) && callee.text === name;
  });
}

/**
 * The INPUT type of the first Standard Schema handed to a pipe in these decorator
 * arguments (`new ZodPipe(schema)`, `new ValibotPipe(schema)`), or null.
 */
function pipeSchemaInput(checker: ts.TypeChecker, args: readonly ts.Expression[]): ts.Type | null {
  for (const arg of args) {
    if (!ts.isNewExpression(arg) && !ts.isCallExpression(arg)) continue;
    for (const candidate of arg.arguments ?? []) {
      const input = standardSchemaInput(checker, checker.getTypeAtLocation(candidate));
      if (input) return input;
    }
  }
  return null;
}

/** `T['~standard']['types']['input']` of a Standard Schema type, or null. */
function standardSchemaInput(checker: ts.TypeChecker, schema: ts.Type): ts.Type | null {
  const standard = checker.getPropertyOfType(schema, '~standard');
  if (!standard) return null;
  const types = checker.getPropertyOfType(checker.getTypeOfSymbol(standard), 'types');
  if (!types) return null;
  const input = checker.getPropertyOfType(
    checker.getNonNullableType(checker.getTypeOfSymbol(types)),
    'input',
  );
  return input ? checker.getTypeOfSymbol(input) : null;
}

/** Resolve the printer's placeholders in a route's type text to `prefix` + name. */
function bindRefs(route: RouteDescriptor, prefix: string): RouteDescriptor {
  const cs = route.contract?.contractSource;
  if (!cs?.standalone) return route;
  const bind = <T extends string | null | undefined>(text: T): T =>
    (typeof text === 'string' ? text.split(REF).join(prefix) : text) as T;
  return {
    ...route,
    contract: {
      ...route.contract,
      contractSource: {
        ...cs,
        response: bind(cs.response),
        body: bind(cs.body),
        query: bind(cs.query),
      },
    },
  };
}

// ---------------------------------------------------------------------------
// Type printing
// ---------------------------------------------------------------------------

/** Library types printed by name — the client has them too (and `Jsonify` knows them). */
const GLOBAL_BUILTINS = new Set([
  'Date',
  'RegExp',
  'Map',
  'Set',
  'ReadonlyMap',
  'ReadonlySet',
  'ArrayBuffer',
  'Uint8Array',
  'Blob',
  'File',
  'URL',
  'Error',
]);

/** Deepest structural nesting printed inline before degrading to `unknown`. */
const MAX_DEPTH = 12;

class TypePrinter {
  /** Hoisted named types, by symbol → emitted name. */
  private readonly names = new Map<ts.Symbol, string>();
  private readonly taken = new Set<string>();
  private readonly bodies: string[] = [];
  /** Anonymous types currently being printed — a revisit is a cycle. */
  private readonly inProgress = new Set<ts.Type>();

  constructor(
    private readonly checker: ts.TypeChecker,
    private readonly program: ts.Program,
  ) {}

  declarations(): string[] {
    return this.bodies;
  }

  print(type: ts.Type): string {
    return this.type(type, 0);
  }

  private type(type: ts.Type, depth: number): string {
    const f = type.flags;
    if (f & (ts.TypeFlags.Any | ts.TypeFlags.Unknown)) return 'unknown';
    if (f & ts.TypeFlags.Never) return 'never';
    if (f & ts.TypeFlags.Void) return 'void';
    if (f & ts.TypeFlags.Undefined) return 'undefined';
    if (f & ts.TypeFlags.Null) return 'null';
    if (f & ts.TypeFlags.StringLiteral) return JSON.stringify((type as ts.StringLiteralType).value);
    if (f & ts.TypeFlags.NumberLiteral) return String((type as ts.NumberLiteralType).value);
    if (f & ts.TypeFlags.BigIntLiteral) {
      const v = (type as ts.BigIntLiteralType).value;
      return `${v.negative ? '-' : ''}${v.base10Value}n`;
    }
    if (f & ts.TypeFlags.BooleanLiteral) {
      return (type as { intrinsicName?: string }).intrinsicName === 'true' ? 'true' : 'false';
    }
    if (f & (ts.TypeFlags.String | ts.TypeFlags.TemplateLiteral | ts.TypeFlags.StringMapping))
      return 'string';
    if (f & ts.TypeFlags.Number) return 'number';
    if (f & ts.TypeFlags.Boolean) return 'boolean';
    if (f & ts.TypeFlags.BigInt) return 'bigint';
    if (f & ts.TypeFlags.ESSymbolLike) return 'symbol';
    if (f & ts.TypeFlags.NonPrimitive) return 'object';
    if (f & (ts.TypeFlags.TypeParameter | ts.TypeFlags.Index | ts.TypeFlags.IndexedAccess))
      return 'unknown';
    if (f & (ts.TypeFlags.Conditional | ts.TypeFlags.Substitution)) return 'unknown';

    const hoisted = this.hoist(type);
    if (hoisted) return hoisted;

    if (type.isUnion()) return this.union(type.types, depth);
    if (type.isIntersection()) {
      return type.types.map((t) => this.parenthesize(this.type(t, depth))).join(' & ');
    }
    if (f & ts.TypeFlags.Object) return this.object(type as ts.ObjectType, depth);
    return 'unknown';
  }

  private union(members: readonly ts.Type[], depth: number): string {
    const printed: string[] = [];
    let hasTrue = false;
    let hasFalse = false;
    for (const m of members) {
      const text = this.type(m, depth);
      if (text === 'true') hasTrue = true;
      else if (text === 'false') hasFalse = true;
      else printed.push(this.parenthesize(text));
    }
    if (hasTrue && hasFalse) printed.push('boolean');
    else if (hasTrue) printed.push('true');
    else if (hasFalse) printed.push('false');
    const unique = [...new Set(printed)];
    return unique.length === 0 ? 'never' : unique.join(' | ');
  }

  /**
   * Parenthesize a function type inside a union/intersection/optional tuple slot.
   * (TS normalizes `A & (B | C)` to a union of intersections, so an intersection
   * member is never itself a union.)
   */
  private parenthesize(text: string): string {
    return text.startsWith('(') && text.includes(') =>') ? `(${text})` : text;
  }

  private object(type: ts.ObjectType, depth: number): string {
    const checker = this.checker;
    if (checker.isArrayType(type)) {
      const [element] = checker.getTypeArguments(type as ts.TypeReference);
      return `Array<${element ? this.type(element, depth + 1) : 'unknown'}>`;
    }
    if (checker.isTupleType(type)) return this.tuple(type as ts.TypeReference, depth);

    const symbol = type.getSymbol();
    const named = ts.SymbolFlags.Interface | ts.SymbolFlags.Class;
    if (symbol && symbol.flags & named && this.isLibSymbol(symbol)) {
      if (!GLOBAL_BUILTINS.has(symbol.name)) {
        // Promise nested in a payload, Function, … — nothing a client can receive.
        if (type.getCallSignatures().length > 0) return '(...args: never[]) => unknown';
        return 'unknown';
      }
      const args =
        type.objectFlags & ts.ObjectFlags.Reference
          ? checker.getTypeArguments(type as ts.TypeReference)
          : [];
      return args.length > 0
        ? `${symbol.name}<${args.map((a) => this.type(a, depth + 1)).join(', ')}>`
        : symbol.name;
    }
    // A class from a dependency carries behavior; its JSON shape is not its type.
    if (symbol && symbol.flags & ts.SymbolFlags.Class && this.isExternalSymbol(symbol)) {
      return 'unknown';
    }

    const props = checker.getPropertiesOfType(type);
    const calls = type.getCallSignatures();
    if (calls.length > 0 && props.length === 0) return '(...args: never[]) => unknown';

    if (depth >= MAX_DEPTH || this.inProgress.has(type)) return 'unknown';
    this.inProgress.add(type);
    try {
      const members: string[] = [];
      for (const info of checker.getIndexInfosOfType(type)) {
        const key = info.keyType.flags & ts.TypeFlags.Number ? 'number' : 'string';
        members.push(`[key: ${key}]: ${this.type(info.type, depth + 1)}`);
      }
      const isClass = !!(symbol && symbol.flags & ts.SymbolFlags.Class);
      for (const prop of props) {
        if (!this.isDataProperty(prop, isClass)) continue;
        const optional = !!(prop.flags & ts.SymbolFlags.Optional);
        const propType = checker.getTypeOfSymbol(prop);
        // `x?: T` already says "may be absent"; drop the `| undefined` strict mode adds.
        const text =
          optional && propType.isUnion() && !propType.aliasSymbol
            ? this.union(
                propType.types.filter((t) => !(t.flags & ts.TypeFlags.Undefined)),
                depth + 1,
              )
            : this.type(propType, depth + 1);
        members.push(`${propertyKey(prop.name)}${optional ? '?' : ''}: ${text}`);
      }
      return members.length > 0 ? `{ ${members.join('; ')} }` : '{}';
    } finally {
      this.inProgress.delete(type);
    }
  }

  private tuple(type: ts.TypeReference, depth: number): string {
    const target = type.target as ts.TupleType;
    const elements = this.checker.getTypeArguments(type).map((t, i) => {
      const flags = target.elementFlags[i] ?? ts.ElementFlags.Required;
      const text = this.type(t, depth + 1);
      if (flags & ts.ElementFlags.Rest) return `...Array<${text}>`;
      if (flags & ts.ElementFlags.Variadic) return `...${text}`;
      if (flags & ts.ElementFlags.Optional) return `${this.parenthesize(text)}?`;
      return text;
    });
    return `[${elements.join(', ')}]`;
  }

  /** Own data fields as JSON carries them: no methods, symbol keys, or non-public members. */
  private isDataProperty(prop: ts.Symbol, isClass: boolean): boolean {
    if (prop.name.startsWith('__@') || prop.name.startsWith('#')) return false;
    if (prop.flags & ts.SymbolFlags.Method) return false;
    // A class getter lives on the prototype — JSON.stringify never sees it.
    if (isClass && prop.flags & ts.SymbolFlags.Accessor) return false;
    const decl = prop.valueDeclaration;
    if (
      decl &&
      ts.getCombinedModifierFlags(decl) & (ts.ModifierFlags.Private | ts.ModifierFlags.Protected)
    )
      return false;
    return true;
  }

  /**
   * A reference to a hoisted declaration when `type` is a named, non-generic type
   * declared in the app: a type alias, an interface, a class, or an enum.
   */
  private hoist(type: ts.Type): string | null {
    const alias = type.aliasSymbol;
    if (alias && !type.aliasTypeArguments?.length && this.isAppSymbol(alias)) {
      return this.reference(alias, type);
    }
    const symbol = type.getSymbol();
    if (!symbol || !this.isAppSymbol(symbol)) return null;
    const namedKinds = ts.SymbolFlags.Interface | ts.SymbolFlags.Class | ts.SymbolFlags.Enum;
    if (!(symbol.flags & namedKinds)) return null;
    // `Page<User>` — an instantiation is inlined; only the plain declaration is named.
    if (
      type.flags & ts.TypeFlags.Object &&
      (type as ts.ObjectType).objectFlags & ts.ObjectFlags.Reference &&
      this.checker.getTypeArguments(type as ts.TypeReference).length > 0
    ) {
      return null;
    }
    // A single enum member (`Role.Admin`) prints as its literal.
    if (symbol.flags & ts.SymbolFlags.EnumMember) return null;
    return this.reference(symbol, type);
  }

  private reference(symbol: ts.Symbol, type: ts.Type): string {
    const existing = this.names.get(symbol);
    if (existing) return `${REF}${existing}`;
    const name = this.claimName(symbol.name);
    this.names.set(symbol, name);
    // Reserve first so a self-reference inside the body prints the name.
    const index = this.bodies.push('') - 1;
    const body = this.structural(type);
    this.bodies[index] = `export type ${name} = ${body};`;
    return `${REF}${name}`;
  }

  /** Print a hoisted type's body — its structure, not a reference to itself. */
  private structural(type: ts.Type): string {
    if (type.isUnion()) return this.union(type.types, 0);
    if (type.isIntersection()) {
      return type.types.map((t) => this.parenthesize(this.type(t, 0))).join(' & ');
    }
    if (type.flags & ts.TypeFlags.Object) return this.object(type as ts.ObjectType, 0);
    return this.type(type, 0);
  }

  private claimName(raw: string): string {
    const base = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(raw) && raw !== 'default' ? raw : 'Anonymous';
    let name = base;
    for (let n = 2; this.taken.has(name); n++) name = `${base}${n}`;
    this.taken.add(name);
    return name;
  }

  private isLibSymbol(symbol: ts.Symbol): boolean {
    const decls = symbol.getDeclarations() ?? [];
    return (
      decls.length > 0 &&
      decls.every((d) => this.program.isSourceFileDefaultLibrary(d.getSourceFile()))
    );
  }

  private isExternalSymbol(symbol: ts.Symbol): boolean {
    const decls = symbol.getDeclarations() ?? [];
    return decls.length > 0 && decls.every((d) => isExternal(d.getSourceFile().fileName));
  }

  /** Declared in the app's own source (not a dependency, not the TS lib). */
  private isAppSymbol(symbol: ts.Symbol): boolean {
    const decls = symbol.getDeclarations() ?? [];
    if (decls.length === 0) return false;
    return decls.every((d) => {
      const sf = d.getSourceFile();
      return !this.program.isSourceFileDefaultLibrary(sf) && !isExternal(sf.fileName);
    });
  }
}

function isExternal(fileName: string): boolean {
  if (fileName.includes(`${sep}node_modules${sep}`) || fileName.includes('/node_modules/'))
    return true;
  try {
    return realpathSync(fileName).includes(`${sep}node_modules${sep}`);
  } catch {
    return false;
  }
}

function propertyKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}
