import { mkdir, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';
import type { DiscoveredPage } from '../discovery/pages.js';
import type { SharedPropsResult } from '../discovery/shared-props.js';

export interface EmitPagesOptions {
  /** The export name to reference in import() type expressions (default: 'ComponentProps'). */
  propsExport?: string;
  /** When true, infer props from the default export's first parameter instead of a named export. */
  inferFromDefault?: boolean;
  /** When provided, emit an InertiaSharedProps augmentation alongside the pages. */
  sharedProps?: SharedPropsResult | null;
}

export async function emitPages(
  pages: DiscoveredPage[],
  outDir: string,
  _options: EmitPagesOptions = {},
): Promise<void> {
  await mkdir(outDir, { recursive: true });

  const pageNameUnion =
    pages.length > 0 ? pages.map((p) => JSON.stringify(p.name)).join(' | ') : 'never';

  const augBody = pages
    .map((p) => {
      const key = needsQuotes(p.name) ? JSON.stringify(p.name) : p.name;
      const valueType = buildAugmentationType(p, outDir);
      return `    ${key}: ${valueType};`;
    })
    .join('\n');

  const propsHelper =
    "\nexport type InertiaProps<K extends InertiaPageName> = import('@dudousxd/nestjs-inertia').InertiaPages[K];\n";

  const sharedPropsBlock = buildSharedPropsBlock(_options.sharedProps ?? null);
  const scopesBlock = buildScopesBlock(pages);

  const content = `// Generated by @dudousxd/nestjs-codegen. Do not edit.\n\nexport type InertiaPageName = ${pageNameUnion};\n${propsHelper}${scopesBlock}\ndeclare module '@dudousxd/nestjs-inertia' {\n  interface InertiaPages {\n${augBody}\n  }\n${sharedPropsBlock}}\n`;

  await writeFile(join(outDir, 'pages.d.ts'), content, 'utf8');
}

/**
 * With more than one Inertia app (`pages.scopes`), the page names of each scope:
 * `InertiaScopePages` (scope → union of its page names) and `InertiaScopePageName<S>`. An app's
 * client can type its page resolver or a `usePage().component` check with its own scope's names.
 * Empty (nothing emitted) for a single-app project.
 */
function buildScopesBlock(pages: DiscoveredPage[]): string {
  const byScope = new Map<string, string[]>();
  for (const page of pages) {
    const scope = page.scope ?? 'default';
    const names = byScope.get(scope) ?? [];
    names.push(JSON.stringify(page.name));
    byScope.set(scope, names);
  }
  if (![...byScope.keys()].some((scope) => scope !== 'default')) return '';
  if (!byScope.has('default')) byScope.set('default', []);
  const scopes = ['default', ...[...byScope.keys()].filter((s) => s !== 'default')];
  const body = scopes
    .map((scope) => {
      const key = needsQuotes(scope) ? JSON.stringify(scope) : scope;
      const names = byScope.get(scope) ?? [];
      return `  ${key}: ${names.length ? names.join(' | ') : 'never'};`;
    })
    .join('\n');
  return `\n/** The page names of each Inertia app: \`default\` (forRoot) and every \`pages.scopes\` entry. */\nexport interface InertiaScopePages {\n${body}\n}\n\nexport type InertiaScopePageName<S extends keyof InertiaScopePages> = InertiaScopePages[S];\n`;
}

/**
 * Build the `InertiaSharedProps` interface augmentation block.
 * Returns an empty string when sharedProps is null (graceful fallback).
 *
 * When `isImportRef` is true, the type is expressed as a mapped type from an import reference.
 * When `properties` are available, they are emitted as individual interface members.
 */
function buildSharedPropsBlock(sharedProps: SharedPropsResult | null): string {
  if (!sharedProps) return '';

  // isImportRef case: emit a type alias that re-exports the external type
  if (sharedProps.isImportRef) {
    return `\n  // eslint-disable-next-line @typescript-eslint/no-empty-interface\n  interface InertiaSharedProps extends ${sharedProps.typeString} {}\n`;
  }

  // Inline properties case
  if (!sharedProps.properties || sharedProps.properties.length === 0) return '';

  const propsBody = sharedProps.properties.map((p) => `    ${p.name}: ${p.type};`).join('\n');

  return `\n  interface InertiaSharedProps {\n${propsBody}\n  }\n`;
}

/**
 * Build the type for a page in the module augmentation.
 * Uses `Parameters<typeof import('...').default>[0]` to infer props
 * directly from the default export — no named export needed.
 */
function buildAugmentationType(page: DiscoveredPage, outDir: string): string {
  let importPath = relative(outDir, page.absolutePath).replace(/\.(tsx?|vue|svelte)$/, '');
  if (!importPath.startsWith('.')) {
    importPath = `./${importPath}`;
  }
  return `Parameters<typeof import('${importPath}').default>[0]`;
}

function needsQuotes(name: string): boolean {
  return !/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
}
