import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { ValidationAdapter } from '../adapters/types.js';
import type { ResolvedConfig } from '../config/types.js';
import type { RouteDescriptor } from '../discovery/route-model.js';

const HEADER = '// Generated by @dudousxd/nestjs-codegen. Do not edit.';

/** PascalCase base name from a dotted route name. `users.create` → `UsersCreate`. */
function pascal(name: string): string {
  return name
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

interface FormExport {
  routeName: string;
  base: string;
  body?: string; // const name
  query?: string; // const name
}

/**
 * Emits `forms.ts`: one validation schema per route with a `body`/`query` contract,
 * rendered through the active {@link ValidationAdapter}, plus a `formSchemas` map.
 * Returns `true` when a file was written.
 */
export async function emitForms(
  routes: RouteDescriptor[],
  config: ResolvedConfig,
): Promise<boolean> {
  const adapter = config.validation;
  const named = new Map<string, string>(); // hoisted nested schemas (deduped by name)
  const exports: FormExport[] = [];
  const exportConsts: string[] = [];

  for (const route of routes) {
    const c = route.contract;
    if (!c || (!c.body && !c.query)) continue;
    const base = pascal(route.name);
    const entry: FormExport = { routeName: route.name, base };

    if (c.body) {
      const rendered = adapter.renderModule(c.body);
      for (const [n, t] of rendered.namedNestedSchemas) named.set(n, t);
      const constName = `${base}BodySchema`;
      exportConsts.push(`export const ${constName} = ${rendered.schemaText};`);
      entry.body = constName;
    }
    if (c.query) {
      const rendered = adapter.renderModule(c.query);
      for (const [n, t] of rendered.namedNestedSchemas) named.set(n, t);
      const constName = `${base}QuerySchema`;
      exportConsts.push(`export const ${constName} = ${rendered.schemaText};`);
      entry.query = constName;
    }
    exports.push(entry);
  }

  if (exports.length === 0) return false;

  const lines: string[] = [HEADER, ''];
  for (const imp of adapter.importStatements({ used: true })) lines.push(imp);
  lines.push('');
  // Hoisted nested schemas first (referenced by the exports below).
  for (const [n, t] of named) lines.push(`const ${n} = ${t};`);
  if (named.size > 0) lines.push('');
  lines.push(...exportConsts);
  lines.push('');
  const mapEntries = exports.map((e) => {
    const fields: string[] = [];
    if (e.body) fields.push(`body: ${e.body}`);
    if (e.query) fields.push(`query: ${e.query}`);
    return `  ${JSON.stringify(e.routeName)}: { ${fields.join(', ')} },`;
  });
  lines.push('export const formSchemas = {', ...mapEntries, '} as const;', '');

  await mkdir(config.outDir, { recursive: true });
  await writeFile(join(config.outDir, 'forms.ts'), lines.join('\n'), 'utf8');
  return true;
}
