/**
 * MSW + (dependency-free) faker-style mock handler generation.
 *
 * Emits `mocks.ts`: an array of Mock Service Worker (`msw`) `http` handlers, one
 * per contracted route, each returning seeded mock data shaped to the route's
 * response JSON Schema (lowered from the same IR as the OpenAPI export). This is
 * Orval's headline feature; the key difference is we ship NO `@faker-js/faker`
 * dependency — a tiny `mulberry32`-seeded generator (`MOCK_GEN_RUNTIME` in
 * `emit/mock-gen-runtime.ts`) is embedded verbatim into the output, so the
 * generated module is self-contained and deterministic for a given seed.
 *
 * `msw` is a peer dependency the consumer installs; the generated file imports
 * `http`/`HttpResponse` from it. The generator runtime is embedded (not imported)
 * so the file has no dependency on this package at runtime.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { RouteDescriptor } from '../discovery/types.js';
import type { JsonSchema } from '../ir/schema-node-to-json-schema.js';
import { schemaModuleToJsonSchema } from '../ir/schema-node-to-json-schema.js';
import { MOCK_GEN_RUNTIME } from './mock-gen-runtime.js';

export interface MocksEmitOptions {
  /** Output file name within `outDir`. Default `'mocks.ts'`. */
  fileName?: string;
  /** Deterministic seed. Default `1`. */
  seed?: number;
  /** Base URL prepended to handler paths. Default `''`. */
  baseUrl?: string;
}

const REF_PREFIX = '#/components/schemas/';

/** MSW path syntax uses `:param`, which already matches NestJS paths. */
function toMswPath(path: string, baseUrl: string): string {
  return `${baseUrl}${path}`;
}

/**
 * The response schema for a route, lowered from the response IR
 * (`responseSchema`) when present and hoisting its named schemas into the shared
 * `defs` map. Falls back to a permissive schema (the generator then yields a
 * neutral object, which still conforms) when no response IR exists.
 */
function responseSchemaFor(route: RouteDescriptor, defs: Record<string, JsonSchema>): JsonSchema {
  const cs = route.contract!.contractSource;
  if (cs.responseSchema) {
    const { root, named } = schemaModuleToJsonSchema(cs.responseSchema, { refPrefix: REF_PREFIX });
    for (const [name, node] of Object.entries(named)) {
      if (!(name in defs)) defs[name] = node;
    }
    return root;
  }
  return {};
}

/** Build the `mocks.ts` source text. Pure (no I/O). */
export function buildMocksFile(routes: RouteDescriptor[], opts: MocksEmitOptions = {}): string {
  const seed = opts.seed ?? 1;
  const baseUrl = opts.baseUrl ?? '';
  const contracted = routes.filter((r) => r.contract);

  // Shared components map referenced by per-route response schemas.
  const defs: Record<string, JsonSchema> = {};
  const handlers: string[] = [];

  for (const r of contracted) {
    const schema = responseSchemaFor(r, defs);
    const method = r.method.toLowerCase();
    const mswMethod =
      method === 'get' ||
      method === 'post' ||
      method === 'put' ||
      method === 'patch' ||
      method === 'delete'
        ? method
        : 'all';
    const path = toMswPath(r.path, baseUrl);
    const cs = r.contract!.contractSource;
    const schemaLiteral = JSON.stringify(schema);
    const pathLit = JSON.stringify(path);
    if (cs.stream) {
      // SSE/streaming route: return a text/event-stream body with one event.
      handlers.push(
        [
          `  // ${r.name} (stream)`,
          `  http.${mswMethod}(${pathLit}, () => {`,
          `    const value = generateMock(${schemaLiteral}, makeRng(SEED), DEFS);`,
          '    const body = `data: ${JSON.stringify(value)}\\n\\n`;',
          "    return new HttpResponse(body, { headers: { 'Content-Type': 'text/event-stream' } });",
          '  }),',
        ].join('\n'),
      );
    } else {
      handlers.push(
        [
          `  // ${r.name}`,
          `  http.${mswMethod}(${pathLit}, () => {`,
          `    const value = generateMock(${schemaLiteral}, makeRng(SEED), DEFS);`,
          '    return HttpResponse.json(value);',
          '  }),',
        ].join('\n'),
      );
    }
  }

  const lines: string[] = [
    '// Generated by @dudousxd/nestjs-codegen. Do not edit.',
    '// MSW handlers returning deterministic, schema-shaped mock data.',
    '/* eslint-disable */',
    '// @ts-nocheck',
    '',
    "import { http, HttpResponse } from 'msw';",
    '',
    `const SEED = ${seed};`,
    '',
    '// ---------------------------------------------------------------------------',
    '// Embedded mock-data runtime (mulberry32 PRNG + JSON-Schema value generator).',
    '// Dependency-free: no @faker-js/faker. Deterministic for a given SEED.',
    '// ---------------------------------------------------------------------------',
    MOCK_GEN_RUNTIME,
    '',
    '// Shared component schemas referenced by $ref.',
    `const DEFS = ${JSON.stringify(defs, null, 2)};`,
    '',
    '/** MSW request handlers, one per contracted route. */',
    'export const handlers = [',
    ...handlers,
    '];',
    '',
  ];

  return lines.join('\n');
}

/** Emit `mocks.ts` into `outDir`. */
export async function emitMocks(
  routes: RouteDescriptor[],
  outDir: string,
  opts: MocksEmitOptions = {},
): Promise<void> {
  await mkdir(outDir, { recursive: true });
  const content = buildMocksFile(routes, opts);
  const fileName = opts.fileName ?? 'mocks.ts';
  await writeFile(join(outDir, fileName), content, 'utf8');
}

// Re-export the lowering so callers/tests can build richer response schemas when
// response IR becomes available.
export { schemaModuleToJsonSchema, REF_PREFIX };
