import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { RouteDescriptor } from '../discovery/route-model.js';

/**
 * Emits `routes.ts` into `outDir`:
 * - `ROUTES` map (name → path), `RouteName` union
 * - `RouteParams<K>` mapped type (template-literal `infer` over `:param` segments)
 * - a runtime `route(name, params?, query?)` helper
 */
export async function emitRoutes(routes: RouteDescriptor[], outDir: string): Promise<void> {
  await mkdir(outDir, { recursive: true });
  await writeFile(join(outDir, 'routes.ts'), buildRoutesFile(routes), 'utf8');
}

const HEADER = '// Generated by @dudousxd/nestjs-codegen. Do not edit.';

export function buildRoutesFile(routes: RouteDescriptor[]): string {
  if (routes.length === 0) return buildEmpty();

  const entries = routes
    .map((r) => `  ${JSON.stringify(r.name)}: ${JSON.stringify(r.path)},`)
    .join('\n');
  const routeNameUnion = routes.map((r) => `  | ${JSON.stringify(r.name)}`).join('\n');

  return [
    HEADER,
    '',
    '/** Map of route name → path pattern. */',
    'export const ROUTES = {',
    entries,
    '} as const;',
    '',
    '/** Union of all known route names. */',
    'export type RouteName =',
    `${routeNameUnion};`,
    '',
    '/** Extracts path-parameter names from a route path. `ExtractParams<"/users/:id">` → `"id"`. */',
    'export type ExtractParams<Path extends string> =',
    '  Path extends `${string}:${infer Param}/${infer Rest}`',
    '    ? Param | ExtractParams<`/${Rest}`>',
    '    : Path extends `${string}:${infer Param}`',
    '      ? Param',
    '      : never;',
    '',
    '/** Given a `RouteName`, an object with each path param as `string`. */',
    'export type RouteParams<K extends RouteName> =',
    '  ExtractParams<(typeof ROUTES)[K]> extends never',
    '    ? Record<string, never>',
    '    : { [P in ExtractParams<(typeof ROUTES)[K]>]: string };',
    '',
    'export type RouteParamsMap = { [K in RouteName]: RouteParams<K> };',
    '',
    '/**',
    ' * Build a URL from a named route, interpolating path params and appending query.',
    " * @example route('users.show', { id: '42' }) // → '/users/42'",
    ' */',
    'export function route<K extends RouteName>(',
    '  name: K,',
    '  ...args: ExtractParams<(typeof ROUTES)[K]> extends never',
    '    ? [params?: undefined, query?: Record<string, unknown>]',
    '    : [params: RouteParams<K>, query?: Record<string, unknown>]',
    '): string {',
    '  const [params, query] = args as [Record<string, string> | undefined, Record<string, unknown> | undefined];',
    '  const path: string | undefined = ROUTES[name as RouteName];',
    '  if (path === undefined) {',
    "    const available = Object.keys(ROUTES).join(', ');",
    '    throw new Error(`[nestjs-codegen] Route "${String(name)}" does not exist. Available: ${available}`);',
    '  }',
    '  let resolvedPath: string = path;',
    '  if (params) {',
    '    resolvedPath = resolvedPath.replace(/:([^/]+)/g, (_, key) => {',
    '      const val = params[key];',
    '      if (val === undefined) throw new Error(`Missing route param: ${key}`);',
    '      return encodeURIComponent(val);',
    '    });',
    '  }',
    '  if (query && Object.keys(query).length > 0) {',
    '    const qs = new URLSearchParams();',
    '    for (const [k, v] of Object.entries(query)) {',
    '      if (v !== undefined && v !== null) qs.append(k, String(v));',
    '    }',
    '    const qStr = qs.toString();',
    '    if (qStr) {',
    "      const sep = resolvedPath.includes('?') ? '&' : '?';",
    '      resolvedPath = `${resolvedPath}${sep}${qStr}`;',
    '    }',
    '  }',
    '  return resolvedPath;',
    '}',
    '',
  ].join('\n');
}

function buildEmpty(): string {
  return [
    HEADER,
    '',
    'export const ROUTES = {} as const;',
    'export type RouteName = never;',
    'export type ExtractParams<_Path extends string> = never;',
    'export type RouteParams<_K extends RouteName> = Record<string, never>;',
    'export function route(_name: never, _params?: undefined, _query?: Record<string, unknown>): string { return ""; }',
    '',
  ].join('\n');
}
