import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { ResolvedConfig } from '../config/types.js';
import type { RouteDescriptor } from '../discovery/route-model.js';

const HEADER = '// Generated by @dudousxd/nestjs-codegen. Do not edit.';

/**
 * Emits `api.ts`: a nested `api` object keyed by dotted route name. GET routes get
 * a reader, the rest a writer. When `config.query` is on, readers/writers are
 * framework-agnostic TanStack `queryOptions`/`mutationOptions` (from
 * `@tanstack/query-core`); otherwise they are plain typed fetcher calls. All calls
 * go through the runtime `fetcher` (plain mode — no Inertia).
 */
export async function emitApi(routes: RouteDescriptor[], config: ResolvedConfig): Promise<void> {
  await mkdir(config.outDir, { recursive: true });
  await writeFile(join(config.outDir, 'api.ts'), buildApiFile(routes, config), 'utf8');
}

interface TreeNode {
  children: Map<string, TreeNode>;
  leaf?: RouteDescriptor;
}

function buildTree(routes: RouteDescriptor[]): TreeNode {
  const root: TreeNode = { children: new Map() };
  for (const route of routes) {
    const segments = route.name.split('.');
    let node = root;
    for (let i = 0; i < segments.length; i++) {
      const seg = segments[i] as string;
      if (i === segments.length - 1) {
        let child = node.children.get(seg);
        if (!child) {
          child = { children: new Map() };
          node.children.set(seg, child);
        }
        child.leaf = route;
      } else {
        let child = node.children.get(seg);
        if (!child) {
          child = { children: new Map() };
          node.children.set(seg, child);
        }
        node = child;
      }
    }
  }
  return root;
}

function objectKey(seg: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(seg) ? seg : JSON.stringify(seg);
}

function leafExpr(route: RouteDescriptor, config: ResolvedConfig): string {
  const res = route.contract?.responseType ?? 'unknown';
  const bodyType = route.contract?.bodyType ?? 'unknown';
  const isGet = route.method === 'GET';
  const method = route.method.toLowerCase();
  const path = JSON.stringify(route.path);
  const inputType = isGet
    ? '{ params?: Record<string, string>; query?: Record<string, unknown> }'
    : `{ params?: Record<string, string>; query?: Record<string, unknown>; body?: ${bodyType} }`;

  if (config.query) {
    if (isGet) {
      return `(input?: ${inputType}) =>\n      queryOptions({\n        queryKey: [${JSON.stringify(route.name)}, input] as const,\n        queryFn: () => fetcher.get<${res}>(${path}, input),\n      })`;
    }
    return `() =>\n      mutationOptions({\n        mutationFn: (input: ${inputType}) => fetcher.${method}<${res}>(${path}, input),\n      })`;
  }
  if (isGet) {
    return `(input?: ${inputType}) => fetcher.get<${res}>(${path}, input)`;
  }
  return `(input: ${inputType}) => fetcher.${method}<${res}>(${path}, input)`;
}

function renderNode(node: TreeNode, config: ResolvedConfig, indent: string): string {
  // A pure leaf (no children) renders as its callable expression.
  if (node.leaf && node.children.size === 0) {
    return leafExpr(node.leaf, config);
  }
  const inner = `${indent}  `;
  const parts: string[] = [];
  for (const [key, child] of node.children) {
    parts.push(`${inner}${objectKey(key)}: ${renderNode(child, config, inner)},`);
  }
  return `{\n${parts.join('\n')}\n${indent}}`;
}

export function buildApiFile(routes: RouteDescriptor[], config: ResolvedConfig): string {
  const lines: string[] = [HEADER, ''];
  if (routes.length === 0) {
    lines.push('export const api = {} as const;', '');
    return lines.join('\n');
  }
  if (config.query) {
    lines.push("import { mutationOptions, queryOptions } from '@tanstack/query-core';");
  }
  lines.push(`import { fetcher } from '${config.fetcherModule}';`);
  lines.push('');
  const tree = buildTree(routes);
  lines.push(`export const api = ${renderNode(tree, config, '')};`);
  lines.push('');
  return lines.join('\n');
}
